services:
  - type: web
    name: resume-parser-app
    env: python
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_sm"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production 